"""Report generation."""

import json
import os
from datetime import datetime, timezone
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from src.models import BucketReport, CheckStatus, Severity

console = Console()


class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def print_console_report(self, report):
        console.print("")
        console.print("=" * 60, style="bold blue")
        console.print("  Bucket: " + report.bucket_name, style="cyan")
        console.print("  Score: " + str(report.score) + "/100 - " + report.overall_health)
        console.print("=" * 60, style="bold blue")

        table = Table(title="Results", show_lines=True)
        table.add_column("Check", width=25)
        table.add_column("Status", width=8)
        table.add_column("Severity", width=8)
        table.add_column("Message", width=50)
        for r in report.results:
            table.add_row(r.check_name, r.status.value, r.severity.value, r.message)
        console.print(table)

        # Show recommendations
        recs = [r for r in report.results if r.recommendation]
        if recs:
            console.print("")
            console.print("[bold yellow]Recommendations:[/bold yellow]")
            for i, r in enumerate(recs, 1):
                console.print("  " + str(i) + ". [" + r.check_name + "] " + r.recommendation)

        # Show AI analysis
        if report.ai_analysis:
            console.print("")
            console.print(Panel(str(report.ai_analysis), title="AI Analysis", border_style="blue"))
        if report.ai_summary:
            console.print(Panel(str(report.ai_summary), title="AI Summary", border_style="green"))

    def save_json_report(self, report):
        fn = report.bucket_name + "_" + datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S") + ".json"
        fp = os.path.join(self.output_dir, fn)
        with open(fp, "w") as f:
            json.dump(report.to_dict(), f, indent=2, default=str)
        console.print("[green]Saved: " + fp + "[/green]")
        return fp

    def save_html_report(self, report):
        fn = report.bucket_name + "_" + datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S") + ".html"
        fp = os.path.join(self.output_dir, fn)
        with open(fp, "w") as f:
            f.write(self._generate_html(report))
        console.print("[green]Saved: " + fp + "[/green]")
        return fp

    def _generate_html(self, report):
        rows = ""
        for r in report.results:
            sc = "green" if r.status == CheckStatus.PASS else ("red" if r.status == CheckStatus.FAIL else ("orange" if r.status == CheckStatus.WARNING else "blue"))
            rows += "<tr><td>" + r.check_name + "</td><td style=\'color:" + sc + ";font-weight:bold\'>" + r.status.value + "</td><td>" + r.severity.value + "</td><td>" + r.message + "</td></tr>"

        ai_html = ""
        if report.ai_analysis:
            ai_html = "<h2>AI Analysis</h2><div class=\'ai\'>" + str(report.ai_analysis).replace("<", "&lt;").replace(">", "&gt;") + "</div>"

        score_color = "green" if report.score >= 70 else ("orange" if report.score >= 40 else "red")

        return """<!DOCTYPE html>
<html><head><title>S3 Report - """ + report.bucket_name + """</title>
<style>
body{font-family:Arial,sans-serif;background:#0d1117;color:#c9d1d9;padding:20px;max-width:1200px;margin:0 auto}
h1{color:#58a6ff}h2{color:#58a6ff;border-bottom:1px solid #30363d;padding-bottom:10px}
table{width:100%;border-collapse:collapse;margin:20px 0}
th{background:#21262d;padding:12px;text-align:left}
td{padding:12px;border-bottom:1px solid #21262d}
.score{font-size:48px;font-weight:bold;color:""" + score_color + """}
.header{background:linear-gradient(135deg,#1a1f35,#2d1b69);padding:30px;border-radius:12px;margin-bottom:20px}
.ai{background:#161b22;border:1px solid #1f6feb;border-radius:8px;padding:20px;margin:20px 0;white-space:pre-wrap}
</style></head><body>
<div class="header"><h1>S3 Diagnostic Report</h1>
<p>Bucket: <strong>""" + report.bucket_name + """</strong> | Region: """ + report.region + """</p>
<div class="score">""" + str(report.score) + """/100</div>
<p>Health: """ + report.overall_health + """</p></div>
<h2>Results</h2>
<table><tr><th>Check</th><th>Status</th><th>Severity</th><th>Message</th></tr>
""" + rows + """</table>
""" + ai_html + """
<p style="text-align:center;color:#484f58;margin-top:40px">Generated by S3 Troubleshooter AI</p>
</body></html>"""
